version: '3.8'
# Version con flask y postgres corriendo sin certificados ninguno, osea sin ssl
 
services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: 
        context: .
        dockerfile: Dockerfile_app
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development-fulllocal
      - FLASK_APP=FastULFileToCloud
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
    depends_on:
      - db
    volumes:
      - /home/rufus/Descargas/cheat:/cheat
    networks:
      - netjos
 
  db:
    container_name: db
    image: dbuncerted
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - /opt/db:/var/lib/postgresql/data
    networks:
      - netjos

networks:
  netjos:
