FROM python:3.8

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 80

# RUN flask create_database

# CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]

#docker-compose up -d pythonapp

CMD ["uwsgi", "wsgi.ini"]